apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bubblebank.fullname" . }}-config
  labels:
    {{- include "bubblebank.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.application.serverPort | quote }}
  DB_HOST: {{ .Values.postgresql.fullnameOverride | quote }}
  DB_PORT: {{ .Values.postgresql.service.ports.postgresql | quote }}
  DB_NAME: {{ .Values.postgresql.auth.database | quote }}
