apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bubblebank.fullname" . }}-db-credentials
  labels:
    {{- include "bubblebank.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.postgresql.auth.username | quote }}
  DB_PASS: {{ .Values.postgresql.auth.password | quote }}
