apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bubblebank.fullname" . }}
  labels:
    {{- include "bubblebank.labels" . | nindent 4 }}
  {{- include "bubblebank.ingress.annotations" . | nindent 2 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bubblebank.fullname" . }}
                port:
                  number: {{ .Values.application.serverPort }}
