services:
  db:
    image: ${DB_TYPE}:${DB_VERSION}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./volumes/postgres/certs/postgresql-server.crt:/var/lib/postgresql/postgresql-server.crt
      - ./volumes/postgres/certs/postgresql-server.key:/var/lib/postgresql/postgresql-server.key
      - ./volumes/postgres/certs/internal-ca.crt:/var/lib/postgresql/internal-ca.crt
      - ./volumes/postgres/certs/internal-ca.crl:/var/lib/postgresql/internal-ca.crl
      - ./volumes/postgres/config/p_hba.conf:/etc/postgresql/pg_hba.conf
      - ./volumes/postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  data:
