apiVersion: v2
name: nginx-ingress
description: NGINX Ingress Controller for Kind cluster
version: 0.1.0
appVersion: "1.9.4"
type: application

dependencies:
- name: ingress-nginx
  version: "4.8.3"
  repository: "https://kubernetes.github.io/ingress-nginx"

maintainers:
- name: BubbleBank Team
  email: team@bubblebank.local

keywords:
- nginx
- ingress
- controller
- load-balancer
