# Vault configuration
vault:
  enabled: true

  # Injector configuration
  injector:
    enabled: true
    externalVaultAddr: "http://host.docker.internal:8200"
    authPath: "auth/kubernetes"

    # Environment variables
    extraEnvironmentVars:
      VAULT_SKIP_VERIFY: "true"
      VAULT_CACERT: "/vault/tls/ca.crt"

    # Resource limits
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi

    # Volume mounts for CA certificate
    volumes:
      - name: vault-ca
        secret:
          secretName: vault-ca-cert

    volumeMounts:
      - name: vault-ca
        mountPath: /vault/tls
        readOnly: true

    # Webhook configuration
    webhook:
      failurePolicy: Ignore
      timeoutSeconds: 10

  # Disable server (using external Vault)
  server:
    enabled: false

  # Global settings
  global:
    enabled: true
    tlsDisable: false

  # Disable UI
  ui:
    enabled: false

# CA Certificate configuration
caCert:
  # Set to true to create the CA certificate secret
  create: true
  # Base64 encoded CA certificate content
  data: ""

# Target namespace
namespace: vault-system
