apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-test-app
  labels:
    app: vault-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-test-app
  template:
    metadata:
      labels:
        app: vault-test-app
      annotations:
        # Enable Vault injection
        vault.hashicorp.com/agent-inject: "true"

        # Specify Vault role
        vault.hashicorp.com/role: "bubblebank"

        # Skip TLS verification for local development
        vault.hashicorp.com/agent-inject-vault-tls-skip-verify: "true"

        # Inject database config secret
        vault.hashicorp.com/agent-inject-secret-database-config: "secret/data/bubblebank/database"

        # Template for database config (ENV format)
        vault.hashicorp.com/agent-inject-template-database-config: |
          {{- with secret "secret/data/bubblebank/database" -}}
          DB_HOST={{ .Data.data.host }}
          DB_PORT={{ .Data.data.port }}
          DB_NAME={{ .Data.data.name }}
          DB_USER={{ .Data.data.username }}
          DB_PASS={{ .Data.data.password }}
          {{- end -}}

        # Inject API config
        vault.hashicorp.com/agent-inject-secret-api-config: "secret/data/bubblebank/api"

        # Template for API config (JSON format)
        vault.hashicorp.com/agent-inject-template-api-config: |
          {{- with secret "secret/data/bubblebank/api" -}}
          {
            "api_key": "{{ .Data.data.api_key }}",
            "secret_key": "{{ .Data.data.secret_key }}"
          }
          {{- end -}}
    spec:
      serviceAccountName: default
      containers:
      - name: test-app
        image: nginx:alpine
        ports:
        - containerPort: 80
        # Environment variables pointing to injected secrets
        env:
        - name: DB_CONFIG_FILE
          value: "/vault/secrets/database-config"
        - name: API_CONFIG_FILE
          value: "/vault/secrets/api-config"
        # Simple command to show secrets are available
        command: ["/bin/sh"]
        args:
        - -c
        - |
          echo "=== Vault Test App Started ==="
          echo "Waiting for secrets to be injected..."
          while [ ! -f /vault/secrets/database-config ]; do
            echo "Waiting for database-config..."
            sleep 2
          done
          echo "=== Database Config ==="
          cat /vault/secrets/database-config
          echo ""
          echo "=== API Config ==="
          cat /vault/secrets/api-config
          echo ""
          echo "=== Starting nginx ==="
          nginx -g 'daemon off;'
---
apiVersion: v1
kind: Service
metadata:
  name: vault-test-app-service
  labels:
    app: vault-test-app
spec:
  selector:
    app: vault-test-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
